kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: baxd-features-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Mi
