apiVersion: v1
kind: Pod
metadata:
  name: find-the-place-prod
spec:
  containers:
    - name: find-the-place-prod
      image: find_the_place:v2
      ports:
        - containerPort: 80
      env:
        # Define the environment variable
        - name: STAGE
          valueFrom:
            configMapKeyRef:
              name: staging
              key: stage
  restartPolicy: Never