config:
  target: 'http://192.168.99.100:30061'
  phases:
    - duration: 60
      arrivalRate: 20
  defaults:
    headers:
      x-my-service-auth: '987401838271002188298567'
scenarios:
  - flow:
    - get:
        url: "/api"
#change the ip as per minikube.